name: Build and Push Containers

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
      - 'stms.sln'
      - '.github/workflows/*.yml'
      - 'Backend/STMS.Api/Dockerfile'
      - 'Frontend/Dockerfile'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compute lowercase repo owner
        id: owner
        run: |
          owner="${{ github.repository_owner }}"
          owner_lower=$(echo "$owner" | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=$owner_lower" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          # Use the repository root as the build context so the Dockerfile can COPY Backend/
          # (the Dockerfile expects paths relative to the repo root).
          context: .
          file: ./Backend/STMS.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner_lower }}/stms-backend:latest
            ghcr.io/${{ steps.owner.outputs.owner_lower }}/stms-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner_lower }}/stms-frontend:latest
            ghcr.io/${{ steps.owner.outputs.owner_lower }}/stms-frontend:${{ github.sha }}
