name: Build and Push Containers

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
      - 'stms.sln'
      - '.github/workflows/*.yml'
      - 'Backend/STMS.Api/Dockerfile'
      - 'Frontend/Dockerfile'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/STMS.Api
          file: ./Backend/STMS.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/stms-backend:latest
            ghcr.io/${{ github.repository_owner }}/stms-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/stms-frontend:latest
            ghcr.io/${{ github.repository_owner }}/stms-frontend:${{ github.sha }}
