name: Build and Push Containers

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
      - 'stms.sln'
      - '.github/workflows/*.yml'
      - 'Backend/STMS.Api/Dockerfile'
      - 'Frontend/Dockerfile'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compute lowercase repo owner
        id: owner
        run: |
          owner="${{ github.repository_owner }}"
          owner_lower=$(echo "$owner" | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=$owner_lower" >> $GITHUB_OUTPUT

      - name: Set image registry variable
        id: registry
        run: |
          owner=${{ steps.owner.outputs.owner_lower }}
          echo "IMAGE_REGISTRY=ghcr.io/$owner" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "IMAGE_SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with docker compose
        uses: docker/compose-action@v2
        with:
          files: |-
            docker-compose.yml
          run: build --pull --progress=plain
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}

      - name: Tag images with sha and push
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
        run: |
          set -euo pipefail
          echo "Pushing images from docker-compose with registry=${IMAGE_REGISTRY}"

          # The compose file set images to ${IMAGE_REGISTRY}/stms-backend:latest and
          # ${IMAGE_REGISTRY}/stms-frontend:latest. Retag with the commit SHA and push.

          docker image tag ${IMAGE_REGISTRY}/stms-backend:latest ${IMAGE_REGISTRY}/stms-backend:${IMAGE_SHA_TAG}
          docker image tag ${IMAGE_REGISTRY}/stms-frontend:latest ${IMAGE_REGISTRY}/stms-frontend:${IMAGE_SHA_TAG}

          docker push ${IMAGE_REGISTRY}/stms-backend:latest
          docker push ${IMAGE_REGISTRY}/stms-backend:${IMAGE_SHA_TAG}
          docker push ${IMAGE_REGISTRY}/stms-frontend:latest
          docker push ${IMAGE_REGISTRY}/stms-frontend:${IMAGE_SHA_TAG}
