name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  # 1) BUILD
  build:
    name: Build (Backend + Frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Backend (.NET) ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore Backend
        run: dotnet restore Backend/STMS.Api
      - name: Build Backend
        run: dotnet build Backend/STMS.Api --configuration Release --no-restore

      # --- Frontend (Node + pnpm) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Frontend Dependencies
        run: pnpm install
      - name: Build Frontend
        run: pnpm run build

  # 2) TEST
  test:
    name: Test (Backend + Frontend)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Backend Tests ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Test Backend
        run: dotnet test Backend/STMS.Api --no-build --verbosity normal

      # --- Frontend Tests ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Frontend Dependencies
        run: pnpm install
      - name: Test Frontend
        run: npm run test:run 

  # 3) VERIFY
  verify:
    name: Verify / Summary
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Summary
        run: echo "Build and tests completed successfully for $GITHUB_SHA"
